### ISSUE TITLE
NameError: name 'epoch' is not defined

### ISSUE THREAD

**Issue by labor1983** [asnakep/ScheduledBlocks#4]
Hello again,
I get this error when executing the script:

```
Traceback (most recent call last):
  File "ScheduledBlocks.py", line 258, in <module>
    firstSlotOfEpoch = (firstSlot) + (epoch - 211)*epochLength
NameError: name 'epoch' is not defined
```

Hope you find some time - again, thx you for your efforts.

BR, GETI

**Comment by labor1983** [comment]
Update: My mistake. I have used lowercase letters for N, C, P, X

**Comment by asnakep** [comment]
Hello,

this was caused when pressing any other key which wasn't n,c,p,x
today I will update some fixes including this one.

Kind regards,
Emanuele
