### ISSUE TITLE
Libsodium 1.0.18: Attribute Error for Libsodium library

### ISSUE THREAD

**Issue by mohammadsaadraza** [asnakep/ScheduledBlocks#6]
Traceback for the error:
```
Traceback (most recent call last):
  File "/home/ada/git-libs/ScheduledBlocks/ScheduledBlocks.py", line 324, in <module>
    slotLeader = isSlotLeader(slot, activeSlotCoeff, sigma, eta0, poolVrfSkey)
  File "/home/ada/git-libs/ScheduledBlocks/ScheduledBlocks.py", line 310, in isSlotLeader
    cert=vrfEvalCertified(seed,tpraosCanBeLeaderSignKeyVRFb)
  File "/home/ada/git-libs/ScheduledBlocks/ScheduledBlocks.py", line 286, in vrfEvalCertified
    proof = create_string_buffer(libsodium.crypto_vrf_ietfdraft03_proofbytes())
  File "/usr/lib/python3.9/ctypes/__init__.py", line 387, in __getattr__
    func = self.__getitem__(name)
  File "/usr/lib/python3.9/ctypes/__init__.py", line 392, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: /usr/local/lib/libsodium.so: undefined symbol: crypto_vrf_ietfdraft03_proofbytes
```

**Comment by mohammadsaadraza** [comment]
Maybe this python script is incompatible with the recent `libsodium` version. In that case, kindly do mention the correct version.

**Comment by asnakep** [comment]
Hello,

very sorry for delay, I added libsodium instructions

I post here too

After cloning the libsodium repo from github.com/input-output-hk

git clone https://github.com/input-output-hk/libsodium.git

please make sure you use the libsodium version used by cncli

https://github.com/cardano-community/cncli/tree/develop/contrib

where you can find the correct version:

https://github.com/input-output-hk/libsodium/tree/66f017f16633f2060db25e17c170c2afa0f2a8a1

git describe 66f017f16633f2060db25e17c170c2afa0f2a8a1

> 1.0.16-519-g66f017f1

git checkout 1.0.16-519-g66f017f1

./autogen.sh
./configure
make
sudo make install

**Comment by asnakep** [comment]
Issue is closed
